### ISSUE TITLE
Resolving conflicts choosing the newer file (and not always the local deck file) - 1.4.2.

### ISSUE THREAD

**Issue by sleepingpill87** [GedasFX/decky-cloud-save#101]
Hi, I finally solve the "chtimes operation not permitted" by the custom sync root.
But now I wonder if it is possible to resolve the conflicts between two files (older local deck file and newer cloud file, for example) by make the newer file the "winner".
Does the plugin can work like that?

**Comment by GedasFX** [comment]
Hey, on plugin start it pulls data, making remote data "winner". On game close or sync button press it marks the local data as "winner". The loser file gets copied to .conflict or something.

**Comment by sleepingpill87** [comment]
It's all working now. I had to change the sync path to "/" to "/home/deck/". It's all working properly now.
This plugin is becoming a game changer in my opinion. :)

**Comment by GedasFX** [comment]
Hey, if everything works well, can you leave a comment on 
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/637?

**Comment by GedasFX** [comment]
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/637
Merged. Closing.
