### ISSUE TITLE
Can't perform bidirectional sync

### ISSUE THREAD

**Issue by Dorennor** [GedasFX/decky-cloud-save#110]
I'm trying to perform this action with games Dark Souls 3 and Dark Souls 2.
Their save file is one file with this name for DS3: "DS30000.sl2".

I've tried both with folder and file path targeting.
When I play some time on PC (save file linked to Google Cloud client by symbolic link in case of file or junction in case of folder sync), Date of modification is changed.
I press Sync button and get error, plugin just doesn't want to sync it. But From Steam Deck to PC it works.
Can you help me please investigate this problem? I want to use it so much but I just don't have more minds how to fix it.
I will give you all resources (files etc.), logs. what you need, just tell me, I want t help and resolve it, thanks for your time and cool plugin.
I just can't understand why is doesn't work, as I can see comparison of files performs by date of modification and size. Size maybe can be the same but modification 100% different so it just weird :(

**Comment by Dorennor** [comment]
Path of the save on Deck: "/home/deck/.steam/steam/steamapps/compatdata/374320/pfx/drive_c/users/steamuser/Application Data/DarkSoulsIII/0110000118ce1137/DS30000.sl2"

Path of the save on PC: "G:\Мій диск\decky-cloud-save\home\deck\.local\share\Steam\steamapps\compatdata\374320\pfx\drive_c\users\steamuser\AppData\Roaming\DarkSoulsIII\0110000118ce1137\DS30000.sl2"

New file from PC:
[DS30000.zip](https://github.com/user-attachments/files/17823028/DS30000.zip)

Older save from Deck:
[DS30000.sl2.zip](https://github.com/user-attachments/files/17823043/DS30000.sl2.zip)

I use Google Drive desktop client and LinkShellExtension for creating of symlinks.

**Comment by Dorennor** [comment]
Maybe it just doesn't want to compare files which have same size but different modified dates? 
Also here log of Sync process:

![зображення](https://github.com/user-attachments/assets/587234df-c45b-4955-a0ed-2d34e8564f82)

**Comment by GedasFX** [comment]
Hey!
> I press Sync button and get error, plugin just doesn't want to sync it. 

Can you scroll down in logs more or is that it?

**Comment by Dorennor** [comment]
> Hey!
> 
> > I press Sync button and get error, plugin just doesn't want to sync it.
> 
> Can you scroll down in logs more or is that it?

1. I am idiot and didn't know that I can scroll it with touchscreen.
2. I found reason of error. Dwarf Fortress path contains many files and here log of what happened here.

[2024-11-20 10.40.09.log](https://github.com/user-attachments/files/17827928/2024-11-20.10.40.09.log)

3. I tried to remove path of DF but it stucked. It continued trying to sync even after reinstalling of plugin, reconnection to google cloud and resettings settings (removing plugin folder from settings folder inside of homebrew).
4. I fucked up. I didn't help and I wanted to find how to reset in some way pathes and found folder inside of "/home/deck/.cache/rclone/bisync/" path, folder RClone. I saw here some files and it seems that they contained some of useless paths (Dwarf Fortress).
And I thought that deleting them will help, that Rclone/Plugin will recreate them. And here I am - plugin doesn't work at all, at least bisync seems broken 100%.
Here my logs. 
[2024-11-20 10.59.37.log](https://github.com/user-attachments/files/17828020/2024-11-20.10.59.37.log)
[2024-11-20 11.06.09.log](https://github.com/user-attachments/files/17828023/2024-11-20.11.06.09.log)

Unfortunately I deleted files from bin so even can't restore them. What should I do? And if plugin on my side will alive one more time, can you please explain why DF could be a problem? Is there way to fix it?

**Comment by Dorennor** [comment]
Honestly, I'm kinda newcomer for Linux and only with steam deck so it seems I could make something stupid :(

**Comment by GedasFX** [comment]
Honestly... I do not know what the best course of action is. There was a reason why i didn't to add bisync in the first place :D. I still have no time to work (and provide extensive support) for this plugin, and without deeper understanding I am not sure how I can help.

From my understanding, the remote directory does not have DF, and bisync would want to delete DF saves locally (as they do not exist on remote). Running the command `home/deck/homebrew/plugins/decky-cloud-save/bin/rcloneLauncher copy / backend:decky-cloud-save --filter-from /home/deck/homebrew/settings/decky-cloud-save/sync_paths_filter.txt --copy-links --transfers 8 --checkers 16 --log-file "/home/deck/homebrew/logs/decky-cloud-save/manual.log" --log-format none -v --force` Maybe would help, but it will likely just delete everything you have...

**Comment by Dorennor** [comment]
> Honestly... I do not know what the best course of action is. There was a reason why i didn't to add bisync in the first place :D. I still have no time to work (and provide extensive support) for this plugin, and without deeper understanding I am not sure how I can help.
> 
> From my understanding, the remote directory does not have DF, and bisync would want to delete DF saves locally (as they do not exist on remote). Running the command `home/deck/homebrew/plugins/decky-cloud-save/bin/rcloneLauncher copy / backend:decky-cloud-save --filter-from /home/deck/homebrew/settings/decky-cloud-save/sync_paths_filter.txt --copy-links --transfers 8 --checkers 16 --log-file "/home/deck/homebrew/logs/decky-cloud-save/manual.log" --log-format none -v --force` Maybe would help, but it will likely just delete everything you have...

It's ok if it removes files, currently I just don't understand how to recreate cache and make bisync working at least for ds2/3 which have just 1 file D:

**Comment by GedasFX** [comment]
try removing DF from the sync paths? Or does that not work? If you did remove that path maybe its thinking its deleted then? bisync is a mystery to me too :D

**Comment by Dorennor** [comment]
Dude, you are my hero!
Your command didn't work BUT after your advises I've checked log file and found here button Resync and it recreated all files. + I've pushed to cloud from zero all files one more time and it works! Bisync with all files, even with DF works! Dude I love you, cool plugin. Create patreon/donate platform some time

**Comment by Dorennor** [comment]
> try removing DF from the sync paths? Or does that not work? If you did remove that path maybe its thinking its deleted then? bisync is a mystery to me too :D

DF in some moment stucked in RClone, it seems. I`ve removed it but it still didn't work.

**Comment by GedasFX** [comment]
Ayy glad it worked out! 
And yeah, maybe next year when I have more time ^^
