### ISSUE TITLE
It seems that excludtion functionality doesn't work?

### ISSUE THREAD

**Issue by Dorennor** [GedasFX/decky-cloud-save#113]
I've added folder, which contains 1 file I don't want to sync (graphics settings) between PC and Steam Deck.
I added this file to exclude list but it continues to sync.

**Comment by GedasFX** [comment]
can you send me the `sync_paths_filter.txt`?

**Comment by Dorennor** [comment]
Shit, I'm an idiot. A few days I thought why it didn't work. It is not decky cloud save loaded file to cloud, it is broken symlink from PC. Sorry for disturbing <3

**Comment by GedasFX** [comment]
All good :D

**Comment by Dorennor** [comment]
> All good :D

BTW, does exclusion operation work only for uploading to cloud or downloading from cloud too?

**Comment by Dorennor** [comment]
> All good :D

Because it will be cool it works for downloading too.
I have next problem: Hogwarts Legacy steam cloud saves also syncing graphics settings.
So I wanted to use your cool app + Google Drive Windows Desktop Client + HardLinkShell.

But these bastards added settings file into folder with saves. So I was forced to add manually all static 15 save files to sync path.
It works but I don't like how I've did it and also it can be done only with games with limited saves slots.

So if I could stop syncing of this shitty file and still could add full folder for syncing (except of this file) it will be nice :D
