### ISSUE TITLE
Synchronization was working and after manual changes in the save files, it stopped.

### ISSUE THREAD

**Issue by EnsoBrush** [GedasFX/decky-cloud-save#15]
I have two Steam Decks. One for me and one for my wife. But, since we use the same library, I was looking for a solution to sync save files where Steam can't do it.

I installed Prince of Persia The Forgotten Sands on both Steam decks. I installed Decky Cloud Save on both, logged into the same Microsoft account, and pointed to the path to the folder with the save files.

It then worked without any problems. It synced all the files correctly for a very long time. Unfortunately, there is a bug in the game that does not allow you to move on. The only way to get around it is to manually replace one of the save files with one that does not have this bug. I did this and unfortunately after this change the synchronization stopped working. The game works exactly as it should, but the files are no longer synchronized between the two Steam Decks.

I tried reinstalling the plugin, changing the Microsoft account to another and changing the paths on both one folder higher in the path.  None of these things helped :(

Is there any way I can check if these files go to the Microsoft drive at all? Or any other way to check where these files get blocked? Maybe the plugin now identifies these as two different games? But in that case, how do I get it to identify both installations correctly again?

I thought about changing to Dropbox, but it doesn't respond at all to login attempts from the plugin.

**Comment by GedasFX** [comment]
Hey,

I can answer the second part to check if files go to onedrive. This one is simple - open onedrive on the browser or anywhere else and look for 'decky-cloud-save' folder. Over there you will see the file structure as you would expect. If file is there then it works fine.

Second part about uploading - uploads are skipped if destination file time modified is not the same (or later - one of the two). This means that it should keep only the latest version of every save.

Now for the elephant in the room. How did you get sync to work? This is a backup plugin where it only copies saves to cloud storage, and not the other way. Under default configuration I don't see how it was supposed to work in the first place 😮. Any help here would be much appreciated.

**Comment by EnsoBrush** [comment]
Thanks, I found the folder with the save files on onedrive :)

When it comes to file synchronization, I have no idea how I did it. What should happen if I have an older save file on Steam Deck and a newer version on Onedrive? Does the plug-in download the newer file from the cloud? If so, maybe the plug-in didn't see the difference between one Steam Deck and the other and just downloaded the latest save to the other Steam Deck?

If there is no function for downloading save files from the cloud at all, then it is possible that it is my fault. I tried to assimilate exactly such functionality using Syncthing. Theoretically it works, but you have to remember to manually launch the program itself every time you wake up Steam Deck, because it didn't want to run in the background. Syncthing was less convenient than what I thought the plugin was doing. I was sure that I had turned off Syncthing for the duration of the plug-in tests, but it is possible that I did not do so after all. Although I'm sure I did. It's hard for me to say now what exactly happened there in that case. Because if it was Syncthing then it never worked as well as it did when I thought it was the plug-in working. 

The question then is, whether it would be possible, to add such functionality to the plug-in that it downloads a save file from the cloud if it is newer than what is on SteamDeck? That would be exactly what I need! :D

**Comment by GedasFX** [comment]
> Does the plug-in download the newer file from the cloud? 

Nope this is purely a backup plugin. Our first issue (https://github.com/GedasFX/decky-cloud-save/issues/2) talks about bidirectional sync, so it may be enabled down the line, but right now its disabled. If there is enough support and a easy to understand way to implement it, I will add it. Provide feedback there! I have listed all of the concerns I had with it. If you think its workable, I could add it into next release.

**Comment by dJani97** [comment]
Check the file system permissions on the file you edited. It's possible that the file no longer belongs to the same user, and then this plugin may not be able to access it.

You can check the permissions by running this command:

```shell
ls -la /path/to/the/save/file
```
