### ISSUE TITLE
Suggestion - Sync Pre-Existing Provider Folders

### ISSUE THREAD

**Issue by nullvalue003** [GedasFX/decky-cloud-save#16]
Hello!

For a while on Deck, I used symlinks connected to a custom-made Dropbox folder and did the same on my Windows devices to sync files between devices. Would it be possible to add a feature if it's not already, to sync those pre-existing folders on Dropbox instead of creating a new folder entirely?

Thanks a bunch for answering

**Comment by GedasFX** [comment]
It is not the same, but support will be added to rename the folder, in case anyone was curious. https://github.com/GedasFX/decky-cloud-save/issues/20.
