### ISSUE TITLE
Suggestion: automatic backup after specified games are closed

### ISSUE THREAD

**Issue by calebsw83** [GedasFX/decky-cloud-save#22]
Right now automatic backup only works if any game is closed. And while I appreciate that any kind of automatic backup is available, I think it would be nice to have a feature where we could specify a game so that automatic backup only executes after closing that specific title or titles. I know all or nothing is a much simpler approach, but if this isn't too labor intensive a feature to implement, I was curious if it was possible for this to perhaps one day be included with decky cloud save? Thanks for hearing me out even if you can't or don't want to implement this.

**Comment by GedasFX** [comment]
This is something I have tried out in the past and was for sure on my mind. The idea was to have different sync paths for different games, but that quickly ballooned to be out of proportion in scope for a simple plugin.

To add a game whitelist though, might be possible! We can have a button that says "Whitelist/blacklist game for syncing" when the game is running, The problem with this is I am not sure if non-steam game ids are stable. For example, if you add a non-steam game, move binary, and then add the game again, steam may treat it as 2 different games. In any case, this simple solution could be done for sure.

**Comment by GedasFX** [comment]
Unfortunately, this is not a commonly-enough requested feature, and would require a lot of work to get going, so will have to say no...

https://github.com/GedasFX/decky-ludusavi would have this built-in but with my schedule, it seems like will never get around to starting that...
