### ISSUE TITLE
Question on windows desktop compatible version

### ISSUE THREAD

**Issue by SaltySamurai** [GedasFX/decky-cloud-save#25]
Will there be one? I'd love to see the option to backup saves for games on deck and play from the same save file on my desktop too. I also just like the idea of cloud saves for any game on desktop. So is this likely to ever happen?

**Comment by NL-TCH** [comment]
Honestly probably not, this plugin tailored made for the steamdeck and the decky-loader framework. You can just use the one drive or google cloud option on decky-cloud-save, and on your desktop, use the google cloud/ onedrive client to sync the same folders

**Comment by GedasFX** [comment]
There is no plans to make a windows compatible version, I am in the works of making a replacement plugin for this, https://github.com/GedasFX/decky-ludusavi. This will support bisync and have a more  friendly UI.
