### ISSUE TITLE
Can't sync new folder

### ISSUE THREAD

**Issue by grfigueira** [GedasFX/decky-cloud-save#26]
## Description
I can't sync new folders. When I select "Add New Path to Sync" in and navigate to my desired folder, there is no button to use that folder. There used to be a button at the bottom of the page with the description "Use this folder" but it is no longer there.

I already tried restarting the steam deck (multiple times) and I tried versions 1.2.1 and 1.3.1 of the plugin.
My decky is in stable version 2.10.1

## To Reproduce
1. Press "Sync Paths"
2. Press "Add New Path to Sync" in "Includes"
3. Navigate to a folder

There won't be any button to use that folder

## Expected behavior
After navigating to my desired folder, there should be a button to use that folder.

## Screenshot

<img width="598" alt="image" src="https://github.com/GedasFX/decky-cloud-save/assets/24763517/a065e9e8-c829-47be-9e64-2a2fdf2e0f81">

**Comment by GedasFX** [comment]
Hey, duplicate of https://github.com/GedasFX/decky-cloud-save/issues/23. Update Decky loader to pre-release and use 1.3.1. Latest stable version of Decky Loader broke file selection screen.

**Comment by grfigueira** [comment]
oops my bad, didn't see that. It works now! Thanks
