### ISSUE TITLE
Cloud save file location

### ISSUE THREAD

**Issue by Shadowplay9322** [GedasFX/decky-cloud-save#28]
Hi Genius Sir!
I have a problem regarding this cloud saves. I used my Gdrive account as the provider. 
Everytime i closes a game, it did popup cloud save success. But i tried to find the backup files on my gdrive but didnt found it. Please help?

**Comment by GedasFX** [comment]
Hey, do you have your file sync paths configured correctly?

**Comment by Shadowplay9322** [comment]
Sorry for my low experience. Can u share how i can confirm i configured it
correctly?

**Comment by GedasFX** [comment]
Hey, no worries!

This plugin works on a basis where you first need to select the folders you want to back up. You could configure it on the plugin page, I think its "configure sync paths" button.

**Comment by Shadowplay9322** [comment]
Thanks, I'll check it out.
Will reply soon.

**Comment by GedasFX** [comment]
Issue seems to be resolved, reactivate if it wasn't
