### ISSUE TITLE
Suggestion: Different destination folders for different games

### ISSUE THREAD

**Issue by Tobe95** [GedasFX/decky-cloud-save#29]
Hi, first of all thank you for this plugin. It's coming in handy for sure.

I've been using decky-cloud-save for a while now to sync various files besides savegames, like graphics configs, keybindings etc., so when deleting and reinstalling a game later on I don't have to bother with input or optimal graphics settings.

The downside of syncing so many files however is, that it becomes difficult to keep track of which files belong to which game, both in the GUI but also in the cloud itself, especially if you're syncing multiple files from the main game folder and others from the game's proton prefix.

Right now all files in my google drive are stored under:

`/decky-cloud-save/path/to/savefile.txt`

while I would love to have one more folder in between specifying the name of the respective game, like this for example:

`/decky-cloud-save/Call of Duty/path/to/savefile.txt`

I've been reading a bit through the rclone documentation but I'm not sure if what I'm asking for is even possible without running multiple instances of rclone or have decky-cloud-save work on a per game basis via Steam appid as discussed in [Issue #22 ](https://github.com/GedasFX/decky-cloud-save/issues/22).

Since rclone respects symlinks however, a solution I've come up with could be to create a symlink for each game that just links to the root of the filesystem. So creating a symlink with the name "Call of Duty" would allow all files selected via this folder to be saved under `/decky-cloud-save/Call of Duty`.

I'm not sure if this would be a desirable feature for other users to have, considering it creates a lot of folders, but having an option in the GUI to type in the name of a specific game and then have a symlink created in some hidden path like `/.config/decky-cloud-save/` would make it easier to sort and keep track of files on a per game basis.

Apologies if there is already a better way or some config file option that I'm unaware of and thanks for reading.

**Comment by GedasFX** [comment]
Hmm this would definitely be a hurdle to support natively, however I think you could fake it under the filesystem itself using symlinks!

What *should* work is if you have some central folder, call it `/games` where you just back up this one, and have symlinks go from there. So like `/games/CoD` would point to `/home/somewhere-else`. So if you have a path `/home/somewhere-else/data`, on the remote it would/should show up as `/games/CoD/data` as expected.

If this is a wildly requested feature I might add it together with #22, but right now, this workaround should be good.

**Comment by GedasFX** [comment]
Much like #22 This is a good idea, but the development is just not justifiable. Will have to be done in https://github.com/GedasFX/decky-ludusavi
