### ISSUE TITLE
Bucket Names for Google Cloud Storage and AWS S3 have to be Globally Unique

### ISSUE THREAD

**Issue by binaryronin** [GedasFX/decky-cloud-save#30]
I know this is an advanced use case that not many will come across, but when setting up Google Cloud storage with Decky Cloud Save it creates a new bucket in the account named `decky-cloud-save`. The issue is that all buckets in Google Cloud Storage (and AWS S3) have to be globally unique. Which means once a single person sets up this configuration, it will not work for anyone else.

Case in point, I have setup this integration for myself in Google Cloud Storage. It will fail for anyone else trying to use this plugin with Google Cloud storage because I now have this name. You can see the error here when I try to create a bucket with that name in another project I own:

![image](https://github.com/GedasFX/decky-cloud-save/assets/26859485/5fd2e00a-1eb0-45af-9588-d8135a55af21)

**Comment by GedasFX** [comment]
Hey, this is actually somewhat of a supported case, you can change the name of the destination in the configuration. See `plugin.properties` file in the configuration section.

**Comment by GedasFX** [comment]
You will need to go desktop mode for this

**Comment by binaryronin** [comment]
Ah yes I see it now! Sorry about that!

**Comment by GedasFX** [comment]
Yeah it is quite a new development, I didn't really have time to put it on README, will do that now ^^

**Comment by GedasFX** [comment]
Issue seems to be resolved, closing.
