### ISSUE TITLE
Explore ludusavi

### ISSUE THREAD

**Issue by GedasFX** [GedasFX/decky-cloud-save#37]
Bidirection sync support

[More text TODO]

**Comment by GedasFX** [comment]
Using this as a notepad:

1. Opt-in per game. Justification: some files may be huge and user would like to opt out.
2. When opting in, resolve game by steam id to get name, if its real use it, if not oh well.

Concepts: backup to folder then to cloud

General loop:
1. After a game is launched, check if cloud has something to do: `ludusavi cloud download Terraria --api --preview`. If result is not empty, disable autosync until user manually uploads all to cloud or downloads from it.
2. After close `ludusavi backup Terraria`, if configured properly, this should also include cloud upload. If cloud upload fails, disable the game again.

Considerations: custom games are jankily supported, you could do something something custom paths, but its outside the scope of v1

Pitfalls: Paths from linux to windows do not automatically resolve eachother and is generally speaking terrible to learn to use. Does work incredibly as a backup tool, but when it comes to restore mumbo jumbo begins.

**Comment by AkazaRenn** [comment]
> When opting in, resolve game by steam id to get name, if its real use it, if not oh well.

Not sure about others, but to me if Steam Cloud is available I won't bother using the plugin, so it's mostly used with non-steam games or not even a game (loader settings etc.). Would it be better to compare by names?

**Comment by GedasFX** [comment]
https://github.com/GedasFX/decky-ludusavi Moving Issues and suggestions to there
