### ISSUE TITLE
UI Tweak : Move the toggle "Sync after closing a game"

### ISSUE THREAD

**Issue by NekoGryphou** [GedasFX/decky-cloud-save#38]
Hi,

I've noticed that the **Sync after closing a game** switch first can sometimes be a bit annoying when you want to quickly click on the **Sync Now** button.

What's more, once this switch is activated / deactivated, it's not often touched again, which suggests that it's not necessarily the most central feature of the menu.

Wouldn't it make sense to move this switch a little lower ? In the **Configuration** section for example, since technically it's a configuration.
It could really make use more fluid and intuitive !

Thanks in advance and looking forward to seeing this little improvement ! 😊

----
PS : I can do it and create a PR if you want !

**Comment by GedasFX** [comment]
Sorry, I somehow completely missed this :/

This is a great idea, and if you still want to make a PR feel free. Ill have a break in a few weeks to implement this though regardless. That button should be the first thing 😄

**Comment by NekoGryphou** [comment]
I've pushed you a merge request #67 !
