### ISSUE TITLE
Suggestion: customized cloud sync path

### ISSUE THREAD

**Issue by AkazaRenn** [GedasFX/decky-cloud-save#41]
Currently on OneDrive, saved files are put on the root path of the storage. It makes a bit if trouble for people like me who likes to organize the folders well. It would be a good idea to have a customized path on the cloud storage to save all the files instead.

**Comment by AkazaRenn** [comment]
I just looked at the source code, is there a hidden config entry called "destination_directory" that can do it?

**Comment by GedasFX** [comment]
yeah its in plugin.properties, that would do it.
