### ISSUE TITLE
Suggestion - Sync the setting file with the game saves

### ISSUE THREAD

**Issue by BitMatrix10** [GedasFX/decky-cloud-save#49]
Add the config file in a sub folder of the synced game saves.

After I soft bricked my SteamDeck all my saves were still available because of this tool, which is amazing. But I then had to manually re-apply all the folders I wanted to sync, which was kinda painful.

The suggestion would be, that the config file (there is probably one file lying around which has all the infos which folders to sync in it) will be synced to the same cloud folder as all the other files.

Then if you reinstall decky cloud save it recognizes, that there is a conig file in the OneDrive / DropBox and asks you if you want to import all previous paths. Also a possibility to import a config file manually would be nice, that way you could even give a config file to a friend, which uses the same games.

**Comment by GedasFX** [comment]
For backing up the config, in a way you could do it by just adding a sync path for the following:
```
/home/deck/homebrew/settings/decky-cloud-save/rclone.conf <- The keys for configuration
/home/deck/homebrew/settings/decky-cloud-save/plugin.properties <- plugin config
/home/deck/homebrew/settings/decky-cloud-save/sync_paths.txt <- includes
/home/deck/homebrew/settings/decky-cloud-save/sync_paths_excludes.txt <- excludes
```

After you put the files back on deck it should restore functionality completely.

As for native support to do this, if there is more demand for this feature, I will add it.
