### ISSUE TITLE
Update rclone to 1.65.1

### ISSUE THREAD

**Issue by TJSomething** [GedasFX/decky-cloud-save#50]
My files weren't syncing to Dropbox. I tried the dry run and found I'm running into https://github.com/rclone/rclone/issues/6376. It looks like it got fixed in rclone 1.62, but the included version is 1.61. I just tried upgrading `bin/rclone` and it looks like it fixed the issue. Would it be possible to update the binary in the release?

**Comment by GedasFX** [comment]
Hey, will you be able to test it on the store process?

**Comment by TJSomething** [comment]
Well, I just installed the new release and it looks like it works great.
