### ISSUE TITLE
Sync Failed

### ISSUE THREAD

**Issue by hmduc1603** [GedasFX/decky-cloud-save#53]
Hi,

I encountered sync failed message on my steam deck
"Sync Failed: Run journalctl -u plugin_loader.ser"

**Comment by GedasFX** [comment]
Hey, please run this command:
https://github.com/GedasFX/decky-cloud-save#troubleshooting

**Comment by hmduc1603** [comment]
![IMG_3214](https://github.com/GedasFX/decky-cloud-save/assets/90256010/ea4edd30-ede1-46ee-8942-aacb7a1dcde7)

I have run the command.

**Comment by GedasFX** [comment]
Hmm I dont think I ever seen this issue before.

Try deleting `/home/deck/homebrew/settings/decky-cloud-save/rclone.conf` and resetup backend

**Comment by GedasFX** [comment]
Closing as stale, reopen if issue persists.
