### ISSUE TITLE
Bidirectional Sync Error "Safety Abort: all files were changed on Path 2"

### ISSUE THREAD

**Issue by BigPrimeNumbers** [GedasFX/decky-cloud-save#62]
I'm seeing the following error whenever I run bidirectional sync after I've updated a save file from Windows 11: 

`"Error : Safety abort: all files were changed on Path2 "backend:decky-cloud-save/". Run with --force if desired.`

If I run `~/homebrew/plugins/decky-cloud-save/rclone bisync --filter-from ~/homebrew/settings/decky-cloud-save/sync_paths_filter.txt / backend:decky-cloud-save --copy-links --resync` the files are synced correctly until I update from Windows again. 

Thanks so much for this great plugin. Very excited to see what you do with decky-ludusavi in the future!

**Comment by Emiliopg91** [comment]
a Pull request I made is in progress
if changes are merged to master and released to decky loader store, most problems with bisync will be solved because It will sync automatically before game launch and after game stop and giving "conflict treatment" to every sync.

**Comment by mdeguzis** [comment]
Can you add that rsync/force command to an advanced > troubleshooting section of the README or a wiki page?

**Comment by GedasFX** [comment]
PR is merged, hopefully soon on Beta, this should work much better after

**Comment by GedasFX** [comment]
Looks like will have to resolve --resync issue in another way...
