### ISSUE TITLE
Suggestion: Sync now and put Steam Deck to sleep

### ISSUE THREAD

**Issue by philippthiele** [GedasFX/decky-cloud-save#64]
I am currently playing Cyberpunk on the Steam Deck and I often lock/put the Deck to sleep without closing the game, so I can jump right back into the game. Currently, I am pressing in the plugin "Sync now" before locking and then I wait for 20-60s (depending how many saves need to be synced) until the sync is done and then I put the deck to sleep.

Would it be possible to have an option to sync all the saves and then put the deck automatically to sleep?
I think the sleep feature is a great advantage of the deck, to be able to not start a game whenever I want to play a short while and avoid loading times, but this of course means the saves need to be synced manually, which is fine, but the wait time is then a bit annoying of course.

Great plugin by the way! I love it to know my saves are backed up 😊

**Comment by GedasFX** [comment]
Hello!

To my knowledge there is no way of delaying Deck going to sleep. Not at least with the current plugin permissions 😕

You do not need to launch the game to sync though, you can just click the button "Sync now" and it would take care of it all ^^
________________________________
From: philippthiele ***@***.***>
Sent: Thursday, March 14, 2024 16:15
To: GedasFX/decky-cloud-save ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GedasFX/decky-cloud-save] Suggestion: Sync now and put Steam Deck to sleep (Issue #64)


I am currently playing Cyberpunk on the Steam Deck and I often lock/put the Deck to sleep without closing the game, so I can jump right back into the game. Currently, I am pressing in the plugin "Sync now" before locking and then I wait for 20-60s (depending how many saves need to be synced) until the sync is done and then I put the deck to sleep.

Would it be possible to have an option to sync all the saves and then put the deck automatically to sleep?
I think the sleep feature is a great advantage of the deck, to be able to not start a game whenever I want to play a short while and avoid loading times, but this of course means the saves need to be synced manually, which is fine, but the wait time is then a bit annoying of course.

Great plugin by the way! I love it to know my saves are backed up 😊

**Comment by philippthiele** [comment]
Hi @GedasFX 
thanks for the quick answer. 
I am actually using that "Sync now" button to not need to close the deck. What I meant is, would it be possible to add a button that does "Sync now & put Deck to sleep". 

So it would go like this:
1. I press button "Sync now & put Deck to sleep"
2. decky-cloud-save syncs the save files
3. When the sync is finished, the plugin puts the deck to sleep

**Comment by GedasFX** [comment]
This is theoretically possible I think, more investigating needed. I definitely do not have the time to implement such feature right now though :/

**Comment by philippthiele** [comment]
I researched a bit and tried from the terminal in desktop mode and there at least "systemctl suspend" seemd to be the right command to suspend the deck from software instead of the power button press

**Comment by GedasFX** [comment]
Hey, this would require the plugin to have root access, which I am not planning to ever give.

**Comment by philippthiele** [comment]
@GedasFX makes sense, then this feature probably can never get into main, unless someone finds a way to suspend a steam deck without root. I have made a fork from the repo which adds only this feature and described at the top of the readme which additional setup is necessary to provide a possibility to the plugin to suspend the system: https://github.com/philippthiele/decky-cloud-save

With this, we can close the issue, until someone has a new idea
