### ISSUE TITLE
Sync Now just keeps "rolling"

### ISSUE THREAD

**Issue by joaociocca** [GedasFX/decky-cloud-save#65]
I thought it weird that I it was already over 2 hours of my deck turned on and the "Sync Now" disk icon kept rolling... but thought that maybe I set too many files, so I went to sleep.

It's now been almost 12 hours, and it's still there. I ssh'd into it and couldn't find any processes related to the decky-cloud-save running, no python, no rclone, nothing.

Only thing I can think of dealing with it will be restarting the deck - or at least going to desktop mode then back to gaming mode.

Which led me to question one thing: I can understand if the first sync takes too long, but do sub-sequential syncs attempt to sync all the files all over again, or just a differential sync?

**Comment by GedasFX** [comment]
It's a differential sync. I suspect it may have gotten stuck in some way, as in its not actually syncing and frontend just didn't get the memo.
________________________________
From: João Ciocca ***@***.***>
Sent: Saturday, March 16, 2024 16:55
To: GedasFX/decky-cloud-save ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GedasFX/decky-cloud-save] Sync Now just keeps "rolling" (Issue #65)


I thought it weird that I it was already over 2 hours of my deck turned on and the "Sync Now" disk icon kept rolling... but thought that maybe I set too many files, so I went to sleep.

It's now been almost 12 hours, and it's still there. I ssh'd into it and couldn't find any processes related to the decky-cloud-save running, no python, no rclone, nothing.

Only thing I can think of dealing with it will be restarting the deck - or at least going to desktop mode then back to gaming mode.

Which led me to question one thing: I can understand if the first sync takes too long, but do sub-sequential syncs attempt to sync all the files all over again, or just a differential sync?

**Comment by joaociocca** [comment]
anyway I can help diagnose? I suspect my sometimes bad wifi (it occasionally behaves, I swear) could be the cause =p

**Comment by GedasFX** [comment]
Maybe there could be some logs you can see with `journalctl -f -n 100 -eu plugin_loader` command. Right now I have no ideas...

**Comment by joaociocca** [comment]
no repeats so far, I'll keep it in mind if it happens again

**Comment by GedasFX** [comment]
I'll close this now, reopen if repeats!
