### ISSUE TITLE
authorization doesn't work

### ISSUE THREAD

**Issue by MakaiHanta** [GedasFX/decky-cloud-save#66]
If you open any sh file in the /home/deck/homebrew/plugins/decky-cloud-save/quickstart/ directory, absolutely nothing happens.
If I go to the synchronization menu in game mode and select any provider, the effect is the same

**Comment by GedasFX** [comment]
Hmm try running the scripts from Konsole directly? Could be some UI issue.

**Comment by MakaiHanta** [comment]
> Hmm try running the scripts from Konsole directly? Could be some UI issue.

Apparently, this problem was caused by the system having a default browser selected, which is not installed in principle. I set my own and everything worked in game mode. I really don't understand how the styme browser is connected to the external browser
