### ISSUE TITLE
Pcloud sync fails

### ISSUE THREAD

**Issue by searzh** [GedasFX/decky-cloud-save#69]
![IMG_2077](https://github.com/GedasFX/decky-cloud-save/assets/7809287/b27f5d86-2a82-4a6a-82ac-599da592a0be)

**Comment by GedasFX** [comment]
Does the local rclone config have that section? Plugin uses local config, rather than global one.

**Comment by searzh** [comment]
> Does the local rclone config have that section? Plugin uses local config, rather than global one.

I wouldn’t know. How can I check that and how will it help me fix it? Thanks

**Comment by searzh** [comment]
> What command did you run to set up the rclone.conf originally?

./rclone config

**Comment by GedasFX** [comment]
Sorry, had a hectic few months (wont stop till end of year if that even). Was this eventually resolved? :D

**Comment by searzh** [comment]
> Sorry, had a hectic few months (wont stop till end of year if that even). Was this eventually resolved? :D 

No. I just moved on to one of the default cloud storage options.

**Comment by GedasFX** [comment]
Will mark it as done I guess, we can reopen if needed later ^^
