### ISSUE TITLE
Can't have the 1.4 update from decky loader store 

### ISSUE THREAD

**Issue by Felzow47** [GedasFX/decky-cloud-save#74]
i go to the decky store the lastest is 1.3.5 
![image](https://github.com/GedasFX/decky-cloud-save/assets/49567056/97046e0c-ef32-413e-8474-6efb8dca4dfc)
![image](https://github.com/GedasFX/decky-cloud-save/assets/49567056/502b6680-dbb1-4c79-a38b-2675c7a18351)
And after I try to install it with the zip file from developer menu i downloaded the zip file from the release page but not working:'( 
![image](https://github.com/GedasFX/decky-cloud-save/assets/49567056/dacc96fb-e687-4b81-b663-35de92b906ab)

![image](https://github.com/GedasFX/decky-cloud-save/assets/49567056/02cfae7f-b8f0-498b-b728-6421eb472a9b)

**Comment by GedasFX** [comment]
For the release I will have to check why zip fails to install, but if you wait till Decky team checks, you may find it in the testing store soon enough

**Comment by Felzow47** [comment]
> For the release I will have to check why zip fails to install, but if you wait till Decky team checks, you may find it in the testing store soon enough

ok np ! thx for the fast reply ! i forgoted about the test store 😂 i will try that later
