### ISSUE TITLE
Problem with BiSync

### ISSUE THREAD

**Issue by Felzow47** [GedasFX/decky-cloud-save#78]
i have a problem when syncronise my file from my drop box no changed file just new file that's i added on my computer in the right folder that's decky loader created on my dropbox and when i try to manualy i got so many eror
![Screenshot_20240611_220527](https://github.com/GedasFX/decky-cloud-save/assets/49567056/25138ca8-78e5-4a54-8b13-5ba3c708ce80)
![image](https://github.com/GedasFX/decky-cloud-save/assets/49567056/6a2298a0-afc4-4a34-944b-421287475bb4)

**Comment by Sythog** [comment]
Same error hete

**Comment by GedasFX** [comment]
This is the initial bisyinc run issue. @Emiliopg91, shouldn't there be a button here?

**Comment by GedasFX** [comment]
It also feels like logs are incomplete here? I think its missing the --resync command. I think the final solution would be to just put in docs how to fix.
