### ISSUE TITLE
[Feature request] Backup current config to cloud backend directory

### ISSUE THREAD

**Issue by mdeguzis** [GedasFX/decky-cloud-save#79]
I had to reinstall Decky Loader and lost my sync paths. It would be nice to automatically sync the config file to the root of the cloud save directory.

**Comment by AkazaRenn** [comment]
You can do that by manually adding /home/deck/homebrew/settings/decky-cloud-save to the path list

**Comment by GedasFX** [comment]
Unneeded complexity, and can be easily backed up manually as mentioned by @AkazaRenn
