### ISSUE TITLE
Logs not available in plugin panel

### ISSUE THREAD

**Issue by mdeguzis** [GedasFX/decky-cloud-save#80]
README.md:

> If you are having issues with sync, more often than not, logs will tell you all you need to know to resolve the issue. You can find them in the plugin panel,

**Comment by GedasFX** [comment]
Hey, sorry, yeah the plugin is in a transitional period where we have docs for 1.4. 
Docs for 1.3 are here: https://github.com/GedasFX/decky-cloud-save/blob/06830eb7d65948dd50b6b443a5d1bf12979c329b/README.md

Sorry for the inconvenience :/

**Comment by GedasFX** [comment]
I will keep this open until Decky plugin gets fully merged

**Comment by GedasFX** [comment]
Merged
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/637
