### ISSUE TITLE
Plugin incorrectly identifies some games as the ones with Steam Cloud and doesn't perform cloud sync

### ISSUE THREAD

**Issue by Sythog** [GedasFX/decky-cloud-save#81]
POP WW doesn't support Steam Cloud but the plugin claims that it does.
![20240614190325_1](https://github.com/GedasFX/decky-cloud-save/assets/5557346/bba1b0fb-f272-4f8a-9d9d-6f15e238d7d0)

**Comment by Sythog** [comment]
However, this works on game start
![20240615120030_1](https://github.com/GedasFX/decky-cloud-save/assets/5557346/09f998c6-130c-416a-8c2f-297daef28639)

**Comment by Emiliopg91** [comment]
Have in mind that sync will trigger if the game doesnt Have steam cloud or if user Have it disabledThe check relies on steam game store API, if it is failing its weird, check and tell the result please Enviado de Samsung Mobile
-------- Mensaje original --------De: Ievgen Starodiedov ***@***.***> Fecha: 15/6/24  12:03  (GMT+01:00) Para: GedasFX/decky-cloud-save ***@***.***> Cc: Subscribed ***@***.***> Asunto: Re: [GedasFX/decky-cloud-save] Plugin incorrectly identifies some games as the ones with Steam Cloud and doesn't perform cloud sync (Issue #81) 
However, this works on game start
20240615120030_1.jpg (view on web)

**Comment by Sythog** [comment]
@Emiliopg91 Prince of Perxia: Warrior Within doesn't support the Steam Cloud according to its Steam page. This might be an issue with the Steam API or the API Decky provides to access the game info

**Comment by GedasFX** [comment]
Wait... what's the difference between the first and second pictures?
