### ISSUE TITLE
File picker doesn't work with latest decky loader prerelease

### ISSUE THREAD

**Issue by pizzadude** [GedasFX/decky-cloud-save#85]
The file picker doesn't work with latest decky loader prerelease. ( Clicking to add a folder or file to the sync paths does nothing ). This is on version 1.3.5 from the decky plugin repo. I tried installing the latest 1.4 version of decky-cloud-save from github releases (well, the latest version with a zip) but it got stuck on install.

**Comment by GedasFX** [comment]
Hey, thank you! This is caused by Decky itself. I was told it was fixed now, can you verify?

**Comment by pizzadude** [comment]
After updating decky it works now, thanks for the great work on this plugin!
