### ISSUE TITLE
Reconcile different folder structures between different operating systems, or remove all parent folders option

### ISSUE THREAD

**Issue by georgcmef** [GedasFX/decky-cloud-save#86]
Hello,

I have a game that I want to hop between my SD and windows when playing a nonsteam game. I  am using dropbox as the cloud storage.

When I select the folder for the gamesave in DCS the whole folder path gets saved into Dropbox, e.g. /home/deck/steam/steam/thing/dumb/this/goes/on/forever/almost/there/save.sav

Can the whole directory string be removed? 
I want to make a folder in my dropbox that houses just the files.

**Comment by GedasFX** [comment]
The paths are rclone specific, and the basepath is on root. We could add a dynamic path start, but is it all that necessary?

**Comment by GedasFX** [comment]
Not doing this as it complicates plugin way more than I am able to afford to maintain.
