### ISSUE TITLE
Version 1.4 of decky-cloud-save causes non-steam games to hang on startup.

### ISSUE THREAD

**Issue by pizzadude** [GedasFX/decky-cloud-save#87]
Version 1.4 of decky-cloud-save causes non-steam games (such as flatpaks and appimages) to hang on startup in gaming mode. (It just displays the spinning Steam logo, presumably until the syncing is complete)

This is tested with SteamOS stable and preview / beta.

**Comment by pizzadude** [comment]
It is due to the option "sync on game start & stop". Is there a possibility to add an option to sync on game stop only, which I think was the previous behaviour?

**Comment by GedasFX** [comment]
@pizzadude hey, is bi-sync enabled in here? And also do you have any details how to reproduce better? Tested again and it works... fine?

**Comment by pizzadude** [comment]
Bidirectional sync is disabled. Toast after auto sync is enabled. I don't know of any other details that would help you reproduce the issue.

**Comment by pizzadude** [comment]
I have a lot of sync paths and it takes a while to sync sometimes, so maybe that's it. However, I think there should be an option to sync only upon exiting a game.

**Comment by GedasFX** [comment]
Hmm actually I do not think there's a reason to pull when bisync is disabled. Will have to fix that. But I'm really unsure what would cause it to hang...
