### ISSUE TITLE
A button to pull everything from cloud and overwrite anything on local

### ISSUE THREAD

**Issue by AkazaRenn** [GedasFX/decky-cloud-save#89]
It's an idea to help set up a new system. Currently there would be some conflicts and results in multiple `*.conflict1` files created, and I have to solve them one by one.

**Comment by GedasFX** [comment]
This was a thing I was considering, but ultimately decided against, as this (i want to reiterate) SIMPLE plugin is starting to have button hell of a problem because of bisync.

**Comment by GedasFX** [comment]
Also conflicts are automatically resolved, the missing files are just created. They do not hurt, and can simply be deleted.

**Comment by AkazaRenn** [comment]
> This was a thing I was considering, but ultimately decided against, as this (i want to reiterate) SIMPLE plugin is starting to have button hell of a problem because of bisync.

Makes sense, and for first time set up it actually won't hurt too much to do it manually, given the files are properly structured so I just need to download the whole folder and do an overwrite 😃
