### ISSUE TITLE
Suggestion: Exclude subfolders when selecting folder to sync?

### ISSUE THREAD

**Issue by moukies** [GedasFX/decky-cloud-save#9]
Hello! Sorry if this is not the proper format for this, I'm very new to GitHub and just made this account right now to comment. 

First let me say this is a sensational plugin, and I really appreciate you having made it. It's fantastic for my (and so many others') backup needs, so thank you so much for that!

I do have a suggestion, though: is it possible to have a feature that would disable or exclude certain subfolder while still syncing the main folder? I apologize if this is already a feature, but I did not see it, hence this comment.

To explain my situation: I use this to backup my RetroArch saves so then I can sync them to my other devices. However, because I'm using a texture pack that has to go into the Citra subfolder in the save folder (it's the Henriko Magnifico Legend of Zelda Ocarina of Time and Majora's Mask texture packs) in order for RetroArch to see them and apply them, it takes a long time uploading like 6 GB worth of texture files when backing up my RetroArch saves.

I've tried to upload those files to my Google Drive folder myself so that Decky Cloud Save would hopefully recognize them and skip so it could get to the actual save files and save states that it switches between uploading them and the texture packs, so it's very difficult for me to properly sync the saves/states due to the plugin choosing to prioritize the texture packs instead.

If there was an ability to exclude that Citra subfolder in my saves folder, it would help me immensely and also be just a nifty feature to have.

Is that something that's already available, is possible, or is of interest to you? Either way, thank you for a fantastic plugin!

**Comment by GedasFX** [comment]
Hey!

Dont worry about it! You explained things really well!

For the suggestion, yeah this is likely something we can do 100%, I would just need to figure out the UI for such. Maybe something like:
| Includes                  |       |
|----------------------| -----|
| Add new |  |
| `/home/deck/aaaa/**` | 🚮 |
| `/home/deck/bbbb` |  🚮 |

| Excludes |       |
|----------------------| -----|
| Add new |  |
| `/home/deck/aaaa/sub/**` | 🚮 |


As far as the actual uploading goes, it scans for changed files by time modified. So if the file already exists and time modified is >= than the one on steam deck, then it will skip the upload.

Either way this is important feature and is 100% doable. Just need to verify the UI/UX for it to not be confusing. I presented with an idea, do you think there is a better way?

Would start development either later today or tomorrow.

**Comment by moukies** [comment]
Hello!

Yup, I think having that 'excludes' section and then just selecting the file or folder would be perfect implementation. Alternatively, maybe a pop-up or something could show up and verify if we want to include (all? some?) subfolders, and selecting no would ignore anything that's another folder-deep/beyond what is the selected destination.

I think your idea is probably simpler and more effective, just selecting exactly what you _don't_ want included, for that granular control.

Thank you so much for replying and taking this on. I really appreciate it!!

**Comment by GedasFX** [comment]
Yeah I will likely do the 2 tables approach.

For your idea though I think that would also be possible! They are not mutually exclusive!

When selecting a folder, to import initially you get a popup with options:

```
File
Folder [new]
Folder with subfolders [renamed]
```

I haven't tested it, but I believe it would be possible. Would basically be `/*` instead of `/**`. Let me know if you have better naming here 😄. I am not fond of the long name 😄.

**Comment by moukies** [comment]
Lovely, I simply adore having options haha. This is exquisite, thank you.

Would selecting the folder option mean just whatever is in that specific directory EXCLUDING subfolders, whereas the folder with subfolders option means everything? Am I reading that right? Or is it then opposite way?

Maybe Multi-Layer Folders for the name? It feels long but also short, so take your pick haha.

**Comment by GedasFX** [comment]
```
Folder (include subfolders)
Folder (exclude subfolders)
```

likely would be most understandable :D

**Comment by moukies** [comment]
I think that's the ticket. Very simple and intuitive. Excellent solution!

**Comment by moukies** [comment]
I'm about to head to sleep, but another question before I do: is it possible to select multiple, but not all, files in one go? 

Like if you wanted to sync a handful of files in one folder, would you be able to select them all at one time, or do you have to make a new path to sync for every individual file in that folder that you want synced? 

Or would it be redundant, because you could just select a folder and then with the new exclusion ability we've discussed, it would achieve the same effect/end result?

I'll check back in when I wake up, but what are your thoughts on this? Is this something to consider, enabling the ability to select multiple files to sync at once without having to set a new path to each and every one individually while in that folder, or does this become a non-issue once the exclusion capability comes online?

**Comment by GedasFX** [comment]
We are using the built in decky file picker, so we are effectively at the mercy of them. I dont think its much of a priority right now for them to do this, but you can ask on discord!

Really its more of a technical limitation, rather a design decision currently. Afterwards, if this gets implemented, I think it would still work largely the same, just allowing users to add multiple entries all at once. But right now, we don't have such capabilities sadly :/

**Comment by moukies** [comment]
Gotcha, no worries then. Thanks for confirming with the info.

**Comment by GedasFX** [comment]
PR made: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/313

**Comment by GedasFX** [comment]
Sorry, will have to reopen this as I will need someone to test it. @moukies could you do it?

**Comment by moukies** [comment]
Sure, I'd be delighted. I don't want to mess with the original folder since it finally uploaded all those Citra texture files, but I can try with a new folder pair and see if it excludes the folder/file selected. Is there any specific format I should do with my feedback, when telling you the results?

**Comment by GedasFX** [comment]
In short, decky team does not allow untested plugins to go to store, and usually, plugins get stuck in the testing phase for a while. Instructions for testing are here: https://wiki.deckbrew.xyz/user-guide/testing

you should write a report here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/313

**Comment by moukies** [comment]
Gotcha. I'll try and get it done by tomorrow, or Friday at the latest. Thanks for the info!

**Comment by moukies** [comment]
I left a review yesterday, was that good and/or in line with what's expected for testing plugins?

**Comment by GedasFX** [comment]
Hey thank you! It looked alright, not too sure what else is needed. I will ask around.
