### ISSUE TITLE
Option to add custom rclone arguments like --onedrive-av-override

### ISSUE THREAD

**Issue by AkazaRenn** [GedasFX/decky-cloud-save#90]
If Microsoft thinks the `.exe` file you are downloading is a malware, they decline it for you, and rclone would error due to that. Since we are downloading to a Linux system, I don't think that can do literally any harm to our system.

**Comment by GedasFX** [comment]
We could exclude the .exe files? And if its supposed to be run with wine, then maybe it can? Not too sure how the isolation works here.


also I JUST got notification about this issue? I don't get github sometimes...

**Comment by GedasFX** [comment]
Also, Instead we could have a properties file have "additional arguments" which would be exactly that

**Comment by GedasFX** [comment]
User can manually specify additional arguments to the sync, and that would be it

**Comment by AkazaRenn** [comment]
> User can manually specify additional arguments to the sync, and that would be it

This is a better idea, I've updated the title
