### ISSUE TITLE
Error on bi-sync: "bisync aborted. Must run --resync to recover"

### ISSUE THREAD

**Issue by sleepingpill87** [GedasFX/decky-cloud-save#91]
When I activate bi-sync and I open a non-steam game the result is this error
![20240822_123133](https://github.com/user-attachments/assets/f7f25894-4083-4af7-a7fd-1a75c4a9f1ee)
 I clicked on the button in the sync log ("delete locks"), but it still doesn't work. Plus, I can't see no "resync" button in the log.
While de-activating bi-sync works great when I have to transfert a save from steam deck to pc, but it doesn't work on the other way around.
I'm using dropbox.
Thanks

**Comment by GedasFX** [comment]
Yeah this is an issue, I will add docs for this on the weekend. And maybe we can just push this. You just need to run that command, but I don't have the tools to check right now.

**Comment by GedasFX** [comment]
@sleepingpill87 I think I might have figured it out. Did you by any chance RENAME the destination folder?

**Comment by sleepingpill87** [comment]
> @sleepingpill87 I think I might have figured it out. Did you by any chance RENAME the destination folder?

No, I didn't. I just updated the plugin to the last one (1.4) and activated bisync.

**Comment by GedasFX** [comment]
Can you do 
```
ls -la /home/deck/.cache/rclone/bisync
```

**Comment by sleepingpill87** [comment]
It didn't work.
![20240824_120600](https://github.com/user-attachments/assets/00be50df-0479-49c8-bc73-21ce7b0317e9)
![20240824_120728](https://github.com/user-attachments/assets/ad6d31e0-59d4-4f05-9608-014e86f0347e)

**Comment by GedasFX** [comment]
Hey, update pushed to testing store, does it work now?

**Comment by sleepingpill87** [comment]
Unfortunately no. Like I said in the other thread I'll do "resync now" and this Is the log.
![Uploading 20240901_112950.jpg…]()

**Comment by GedasFX** [comment]
Unfortunately, best you can do is set up custom sync roots now. or delete the culprit file (unsure about consiquences).

To set up custom roots you can follow guide here: https://github.com/GedasFX/decky-cloud-save?tab=readme-ov-file#custom-sync-root

**Comment by sleepingpill87** [comment]
> Unfortunately, best you can do is set up custom sync roots now. or delete the culprit file (unsure about consiquences).
> 
> To set up custom roots you can follow guide here: https://github.com/GedasFX/decky-cloud-save?tab=readme-ov-file#custom-sync-root

I tried, it didn't work (or maybe I'm not so good at that). Do you think the 1.4.2. version can solve the issue?

**Comment by GedasFX** [comment]
Which issue we talking about here? :D 

Without a major breakthrough, it doesn't look very promising, sorry :/

**Comment by sleepingpill87** [comment]
I was talking about the "chtimes operation not permitted" when I click on "resync now". I tried to solve setting up custom root but it didn't work. I'm not so confortable with linux terminal, so maybe I make some mistake. Well, I guess I will wait and see :)
Thx for the help!

**Comment by GedasFX** [comment]
Yeah, I'd consider bisync an advanced feature, so knowing Linux is somewhat a requirement here, as you will encounter issues with conflicts and such down the line anyway.

Don't think I have the capacity to hold the users hand in all of the advanced flows on rclone :/

I will close this ticket as not much more can come out of it here.
