### ISSUE TITLE
Suggestion: Allow users to specify a different destination subfolder for each sync path

### ISSUE THREAD

**Issue by ajburley** [GedasFX/decky-cloud-save#92]
Similarly to #86 I also got frustrated with the long paths for save games - especially when the path does not have the game name inside but some kind of UUID and it's hard to keep track of which game is which. However I had a different idea in mind, why not just let users provide a specific subfolder name for each sync path? There could be a button next to the sync path delete button that let you specify a subfolder name. For example in my Dropbox, I might have /decky-cloud-save/GameName1 and /decky-cloud-save/GameName2 but the actual paths that sync to those destinations could still be things like /run/media/mmcblk0p1/some/long/path/with/uuid/savedir

**Comment by GedasFX** [comment]
Hey, this issue is not really done by the plugin, but by the underlying library. I have had a ludusavi plugin in the works that solves this issue, however life happened and every development is on hold now :/

In general, this feature would be way too complicated to implement.

**Comment by ajburley** [comment]
Thanks a lot for replying! When you say "the underlying library", are you referring to rclone? Should I be raising this issue on their github instead?

**Comment by GedasFX** [comment]
It's not really an issue with rclone. It's more like how it's used. And changing the way it's used would mean changing roots, which would break everything that was configured before.

There might be workarounds for this, but I really have no time to commit to investigation of this.
